# Generated by Django 6.0.2 on 2026-03-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_alter_node_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='cooldown',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1),
        ),
    ]
