# Generated by Django 6.0.2 on 2026-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0002_alter_node_cooldown_alter_node_node_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
